name: BlockHunters
version: 1.0
author: Nick Ryan
main: io.github.thenickryan.blockhunters.BlockHunters
api-version: 1.16
commands:
  blockhunters:
    description: the main BlockHunters command.
    usage: /<command>
    aliases: bh